// Generated by CoffeeScript 1.8.0
module.exports = {
  'password1': {
    cmd: './cmd/iptables.coffee',
    time: 18000,
    arg: 'trusted'
  },
  'password2': {
    cmd: './cmd/iptables.js',
    arg: '2222'
  }
};
